// 30 Ajza' Overview for direct navigation
export const QURAN_AJZA = [
  { juz: 1, nameAr: 'الجزء الأول', startSurah: 1, startAyah: 1, startPage: 1, labelAr: 'الم (الفاتحة - البقرة ١٤١)' },
  { juz: 2, nameAr: 'الجزء الثاني', startSurah: 2, startAyah: 142, startPage: 22, labelAr: 'سَيَقُولُ السُّفَهَاءُ (البقرة ١٤٢ - ٢٥٢)' },
  { juz: 3, nameAr: 'الجزء الثالث', startSurah: 2, startAyah: 253, startPage: 42, labelAr: 'تِلْكَ الرُّسُلُ (البقرة ٢٥٣ - آل عمران ٩٢)' },
  { juz: 4, nameAr: 'الجزء الرابع', startSurah: 3, startAyah: 93, startPage: 62, labelAr: 'لَنْ تَنَالُوا البِرَّ (آل عمران ٩٣ - النساء ٢٣)' },
  { juz: 5, nameAr: 'الجزء الخامس', startSurah: 4, startAyah: 24, startPage: 82, labelAr: 'وَالمُحْصَنَاتُ (النساء ٢٤ - ١٤٧)' },
  { juz: 6, nameAr: 'الجزء السادس', startSurah: 4, startAyah: 148, startPage: 102, labelAr: 'لَا يُحِبُّ اللَّهُ (النساء ١٤٨ - المائدة ٨١)' },
  { juz: 7, nameAr: 'الجزء السابع', startSurah: 5, startAyah: 82, startPage: 121, labelAr: 'وَإِذَا سَمِعُوا (المائدة ٨٢ - الأنعام ١١٠)' },
  { juz: 8, nameAr: 'الجزء الثامن', startSurah: 6, startAyah: 111, startPage: 142, labelAr: 'وَلَوْ أَنَّنَا (الأنعام ١١١ - الأعراف ٨٧)' },
  { juz: 9, nameAr: 'الجزء التاسع', startSurah: 7, startAyah: 88, startPage: 162, labelAr: 'قَالَ المَلَأُ (الأعراف ٨٨ - الأنفال ٤٠)' },
  { juz: 10, nameAr: 'الجزء العاشر', startSurah: 8, startAyah: 41, startPage: 182, labelAr: 'وَاعْلَمُوا (الأنفال ٤١ - التوبة ٩٢)' },
  { juz: 11, nameAr: 'الجزء الحادي عشر', startSurah: 9, startAyah: 93, startPage: 201, labelAr: 'يَعْتَذِرُونَ إِلَيْكُمْ (التوبة ٩٣ - هود ٥)' },
  { juz: 12, nameAr: 'الجزء الثاني عشر', startSurah: 11, startAyah: 6, startPage: 222, labelAr: 'وَمَا مِنْ دَابَّةٍ (هود ٦ - يوسف ٥٢)' },
  { juz: 13, nameAr: 'الجزء الثالث عشر', startSurah: 12, startAyah: 53, startPage: 242, labelAr: 'وَمَا أُبَرِّئُ نَفْسِي (يوسف ٥٣ - إبراهيم ٥٢)' },
  { juz: 14, nameAr: 'الجزء الرابع عشر', startSurah: 15, startAyah: 1, startPage: 262, labelAr: 'رُبَمَا يَوَدُّ (الحجر ١ - النحل ١٢٨)' },
  { juz: 15, nameAr: 'الجزء الخامس عشر', startSurah: 17, startAyah: 1, startPage: 282, labelAr: 'سُبْحَانَ الَّذِي (الإسراء ١ - الكهف ٧٤)' },
  { juz: 16, nameAr: 'الجزء السادس عشر', startSurah: 18, startAyah: 75, startPage: 302, labelAr: 'قَالَ أَلَمْ أَقُلْ (الكهف ٧٥ - طه ١٣٥)' },
  { juz: 17, nameAr: 'الجزء السابع عشر', startSurah: 21, startAyah: 1, startPage: 322, labelAr: 'اقْتَرَبَ لِلنَّاسِ (الأنبياء ١ - الحج ٧٨)' },
  { juz: 18, nameAr: 'الجزء الثامن عشر', startSurah: 23, startAyah: 1, startPage: 342, labelAr: 'قَدْ أَفْلَحَ (المؤمنون ١ - الفرقان ٢٠)' },
  { juz: 19, nameAr: 'الجزء التاسع عشر', startSurah: 25, startAyah: 21, startPage: 362, labelAr: 'وَقَالَ الَّذِينَ (الفرقان ٢١ - النمل ٥٥)' },
  { juz: 20, nameAr: 'الجزء العشرون', startSurah: 27, startAyah: 56, startPage: 382, labelAr: 'فَمَا كَانَ جَوَابَ (النمل ٥٦ - العنكبوت ٤٥)' },
  { juz: 21, nameAr: 'الجزء الحادي والعشرون', startSurah: 29, startAyah: 46, startPage: 402, labelAr: 'وَلَا تُجَادِلُوا (العنكبوت ٤٦ - الأحزاب ٣٠)' },
  { juz: 22, nameAr: 'الجزء الثاني والعشرون', startSurah: 33, startAyah: 31, startPage: 422, labelAr: 'وَمَنْ يَقْنُتْ (الأحزاب ٣١ - يس ٢٧)' },
  { juz: 23, nameAr: 'الجزء الثالث والعشرون', startSurah: 36, startAyah: 28, startPage: 442, labelAr: 'وَمَا أَنْزَلْنَا (يس ٢٨ - الزمر ٣١)' },
  { juz: 24, nameAr: 'الجزء الرابع والعشرون', startSurah: 39, startAyah: 32, startPage: 462, labelAr: 'فَمَنْ أَظْلَمُ (الزمر ٣٢ - فصلت ٤٦)' },
  { juz: 25, nameAr: 'الجزء الخامس والعشرون', startSurah: 41, startAyah: 47, startPage: 482, labelAr: 'إِلَيْهِ يُرَدُّ (فصلت ٤٧ - الجاثية ٣٧)' },
  { juz: 26, nameAr: 'الجزء السادس والعشرون', startSurah: 46, startAyah: 1, startPage: 502, labelAr: 'حم (الأحقاف ١ - الذاريات ٣٠)' },
  { juz: 27, nameAr: 'الجزء السابع والعشرون', startSurah: 51, startAyah: 31, startPage: 522, labelAr: 'قَالَ فَمَا خَطْبُكُمْ (الذاريات ٣١ - الحديد ٢٩)' },
  { juz: 28, nameAr: 'الجزء الثامن والعشرون', startSurah: 58, startAyah: 1, startPage: 542, labelAr: 'قَدْ سَمِعَ (المجادلة ١ - التحريم ١٢)' },
  { juz: 29, nameAr: 'الجزء التاسع والعشرون (تبارك)', startSurah: 67, startAyah: 1, startPage: 562, labelAr: 'تَبَارَكَ الَّذِي (الملك ١ - المرسلات ٥٠)' },
  { juz: 30, nameAr: 'الجزء الثلاثون (عمّ)', startSurah: 78, startAyah: 1, startPage: 582, labelAr: 'عَمَّ يَتَسَاءَلُونَ (النبأ ١ - الناس ٦)' }
];
